Break dependency on python/dist from python/BUILD.bazel (#22633)
#test-continuous

This package referenced things in python/dist, which is not loadable
from other projects since pip deps are marked as `dev_dependency=True`.
This resulted in this error downstream:

```
ERROR: Evaluation of query "deps(//...)" failed: preloading transitive closure failed: error loading package '@@protobuf+//python/dist': Unable to find package for @@[unknown repo 'protobuf_pip_deps' requested from @@protobuf+]//:requirements.bzl: The repository '@@[unknown repo 'protobuf_pip_deps' requested from @@protobuf+]' could not be resolved: No repository visible as '@protobuf_pip_deps' from repository '@@protobuf+'.
```

Since this was only used to determine if the target is macOS, we can use
the platforms definition directly instead.

Fixes https://github.com/protocolbuffers/protobuf/issues/22386

Closes #22633

COPYBARA_INTEGRATE_REVIEW=https://github.com/protocolbuffers/protobuf/pull/22633 from keith:ks/break-dependency-on-python-dist-from-python-build.bazel d06d17ccbe8af7e824e14b8b7bf74bac78f6462c
FUTURE_COPYBARA_INTEGRATE_REVIEW=https://github.com/protocolbuffers/protobuf/pull/22633 from keith:ks/break-dependency-on-python-dist-from-python-build.bazel d06d17ccbe8af7e824e14b8b7bf74bac78f6462c
PiperOrigin-RevId: 794852511